export interface activo {
    id_activo?: string,
    area?: string,
    edificio?: string,
    piso?: string,
    tipo?: string,
    usuario_red?: string,
    hostname?: string,
    direccion_mac?: string,
    direccion_ip?: string,
    reservada_ip?: string,
    id_ultimatix?: string,
    mensaje?: string,
    status?: string,
    timestamp?: string,
    }