Cypress.Commands.add('Activos', (name, lastname) => {
    cy.visit('https://tcs-fe.vercel.app/pages')
    
     cy.wait(1000)
})
beforeEach(() => {
    cy.visit('https://tcs-fe.vercel.app/login')
    cy.get('[placeholder="Ultimatix"]').type('2254001')
    cy.get('[placeholder="Contraseña"]').type('Tcs.@2022')
    cy.get('[class="btn custom-btn shadow w-100"]').click()
      cy.wait(3000)
    cy.get('[buttonname="Registro de activos"]').click()
    cy.get('[buttonname="Registrar activo"]').click()
    })

  
it('Test 1 Registro de un Activo', () => {
    cy.get('#floatingType').select('CPU/Portatil')
    cy.get('[formcontrolname="area"]').select('Recursos Humanos')
    cy.get('[formcontrolname="edificio"]').select('Inluxor')
    cy.get('[formcontrolname="piso"]').select('4')
    cy.get('[formcontrolname="marca"]').type('Asus')
    cy.get('[formcontrolname="modelo"]').type('TUF')
    cy.get('[formcontrolname="serie"]').type('A1MLTFG577852')
    cy.get('[formcontrolname="codigo_barras"]').type('AsusTUFXD')
    cy.get('#floatingHostname').type('caparaz@tcs')
    cy.get('#floatingMAC').type('1C-1B-0D-79-FF-FA')
    cy.get('#floatingIP').type('192.158.1.38')
    cy.get('#floatingReservedIP').select('No')
    cy.get('[formcontrolname="fecha_entrega"]').click('').type('2022-06-21')
    cy.get('.mat-dialog-actions > :nth-child(2) > .mat-button-wrapper').click('')
    cy.get('.swal2-confirm').click('')
    cy.get('#swal2-title').should('have.text','¡Éxito!')

 })
  it('Test 2 Registro de un Activo sin Marca', () => {
    cy.get('[formcontrolname="tipo"]').select('Mouse')
    cy.get('[formcontrolname="area"]').select('CTB')
    cy.get('[formcontrolname="edificio"]').select('Centrum')
    cy.get('[formcontrolname="piso"]').select('4')
    cy.get('#floatingBrand').click('')
    cy.get('[formcontrolname="modelo"]').type('Razorblade')
    cy.get('[formcontrolname="serie"]').type('A1MLTFG577')
    cy.get('[formcontrolname="codigo_barras"]').type('RAZER001')
    cy.get('[formcontrolname="fecha_entrega"]').click('').type('2022-06-21')
    cy.get('.mat-dialog-actions > :nth-child(2) > .mat-button-wrapper').click('')
    cy.get('.form-text').should('have.text' , ' * Ingrese una marca. ')

        })

  it('Test 1 Registro de un Activo sin Modelo', () => {
    cy.get('[formcontrolname="tipo"]').select('Teclado')
    cy.get('[formcontrolname="area"]').select('EnP')
    cy.get('[formcontrolname="edificio"]').select('Condado')
    cy.get('[formcontrolname="piso"]').select('1')
    cy.get('#floatingBrand').type('Logitech')
    cy.get('[formcontrolname="modelo"]').click
    cy.get('[formcontrolname="serie"]').type('G51000')
    cy.get('[formcontrolname="codigo_barras"]').type('LOGI510')
    cy.get('[formcontrolname="fecha_entrega"]').click('').type('2022-06-21')
    cy.get('.mat-dialog-actions > :nth-child(2) > .mat-button-wrapper').click('')
    cy.get('.form-text').should('have.text' , ' * Ingrese un modelo. ')

        }) 
  
  it('Test 3 Registro de un Activo sin Serie', () => {
    cy.get('[formcontrolname="tipo"]').select('Infocus')
    cy.get('[formcontrolname="area"]').select('Seguridad')
    cy.get('[formcontrolname="edificio"]').select('Bosque')
    cy.get('[formcontrolname="piso"]').select('7')
    cy.get('#floatingBrand').type('Samsung')
    cy.get('[formcontrolname="modelo"]').type('InfoSamPro')
    cy.get('[formcontrolname="serie"]').click
    cy.get('[formcontrolname="codigo_barras"]').type('Samif85163')
    cy.get('[formcontrolname="fecha_entrega"]').click('').type('2022-06-21')
    cy.get('.mat-dialog-actions > :nth-child(2) > .mat-button-wrapper').click('')
    cy.get('.form-text').should('have.text' , ' * Ingrese un número de serie. ')
  }) 

  it('Test 4 Registro de un Activo sin Codigo', () => {
    cy.get('[formcontrolname="tipo"]').select('Teléfono')
    cy.get('[formcontrolname="area"]').select('Jurídico')
    cy.get('[formcontrolname="edificio"]').select('Bosque')
    cy.get('[formcontrolname="piso"]').select('10')
    cy.get('#floatingBrand').type('Sony')
    cy.get('[formcontrolname="modelo"]').type('Xperia')
    cy.get('[formcontrolname="serie"]').type('X258716')
    cy.get('[formcontrolname="codigo_barras"]').click
    cy.get('[formcontrolname="fecha_entrega"]').click('').type('2022-06-21')
    cy.get('.mat-dialog-actions > :nth-child(2) > .mat-button-wrapper').click('')
    cy.get('.form-text').should('have.text' , ' * Ingrese el código del activo. ')
  }) 

  it('Test 5 Registro de un Activo sin HostName', () => {
    cy.get('#floatingType').select('CPU/Portatil')
    cy.get('[formcontrolname="area"]').select('Recursos Humanos')
    cy.get('[formcontrolname="edificio"]').select('Inluxor')
    cy.get('[formcontrolname="piso"]').select('4')
    cy.get('[formcontrolname="marca"]').type('Asus')
    cy.get('[formcontrolname="modelo"]').type('TUF')
    cy.get('[formcontrolname="serie"]').type('A1MLTFG577852')
    cy.get('[formcontrolname="codigo_barras"]').type('AsusTUFXD')
    cy.get('#floatingHostname').click('')
    cy.get('#floatingMAC').type('1C-1B-0D-79-FF-FA')
    cy.get('#floatingIP').type('192.158.1.38')
    cy.get('#floatingReservedIP').select('No')
    cy.get('[formcontrolname="fecha_entrega"]').click('').type('2022-06-21')
    cy.get('.mat-dialog-actions > :nth-child(2) > .mat-button-wrapper').click('')
    cy.get('.form-text').should('have.text' , ' * Ingrese un nombre de host. ')
    
 })

 it('Test 6 Registro de un Activo sin MAC', () => {
  cy.get('#floatingType').select('CPU/Portatil')
  cy.get('[formcontrolname="area"]').select('Recursos Humanos')
  cy.get('[formcontrolname="edificio"]').select('Inluxor')
  cy.get('[formcontrolname="piso"]').select('4')
  cy.get('[formcontrolname="marca"]').type('Asus')
  cy.get('[formcontrolname="modelo"]').type('TUF')
  cy.get('[formcontrolname="serie"]').type('A1MLTFG577852')
  cy.get('[formcontrolname="codigo_barras"]').type('AsusTUFXD')
  cy.get('#floatingHostname').type('caparaz@tcs')
  cy.get('#floatingMAC').click('')
  cy.get('#floatingIP').type('192.158.1.38')
  cy.get('#floatingReservedIP').select('No')
  cy.get('[formcontrolname="fecha_entrega"]').click('').type('2022-06-21')
  cy.get('.mat-dialog-actions > :nth-child(2) > .mat-button-wrapper').click('')
  cy.get('.form-text').should('have.text' , ' * Ingrese una dirección MAC. ')
  
})

it('Test 7 Registro de un Activo sin IP', () => {
  cy.get('#floatingType').select('CPU/Portatil')
  cy.get('[formcontrolname="area"]').select('Recursos Humanos')
  cy.get('[formcontrolname="edificio"]').select('Inluxor')
  cy.get('[formcontrolname="piso"]').select('4')
  cy.get('[formcontrolname="marca"]').type('Asus')
  cy.get('[formcontrolname="modelo"]').type('TUF')
  cy.get('[formcontrolname="serie"]').type('A1MLTFG577852')
  cy.get('[formcontrolname="codigo_barras"]').type('AsusTUFXD')
  cy.get('#floatingHostname').type('caparaz@tcs')
  cy.get('#floatingMAC').type('1C-1B-0D-79-FF-FA')
  cy.get('#floatingIP').click('')
  cy.get('#floatingReservedIP').select('No')
  cy.get('[formcontrolname="fecha_entrega"]').click('').type('2022-06-21')
  cy.get('.mat-dialog-actions > :nth-child(2) > .mat-button-wrapper').click('')
  cy.get('.form-text').should('have.text' , ' * Ingrese una dirección IP. ')
  
})
it('Test 8 Registro de un Activo sin Fecha', () => {
  cy.get('#floatingType').select('CPU/Portatil')
  cy.get('[formcontrolname="area"]').select('Recursos Humanos')
  cy.get('[formcontrolname="edificio"]').select('Inluxor')
  cy.get('[formcontrolname="piso"]').select('4')
  cy.get('[formcontrolname="marca"]').type('Asus')
  cy.get('[formcontrolname="modelo"]').type('TUF')
  cy.get('[formcontrolname="serie"]').type('A1MLTFG577852')
  cy.get('[formcontrolname="codigo_barras"]').type('AsusTUFXD')
  cy.get('#floatingHostname').type('caparaz@tcs')
  cy.get('#floatingMAC').type('1C-1B-0D-79-FF-FA')
  cy.get('#floatingIP').type('192.158.1.38')
  cy.get('#floatingReservedIP').select('Sí')
  cy.get('[formcontrolname="fecha_entrega"]').click('')
  cy.get('.mat-dialog-actions > :nth-child(2) > .mat-button-wrapper').click('')
  cy.get('.form-text').should('have.text' , ' * Seleccione una fecha válida. ')
  
})
it('Test 9 Registro de un Activo con fecha futura', () => {
  cy.get('#floatingType').select('CPU/Portatil')
  cy.get('[formcontrolname="area"]').select('Recursos Humanos')
  cy.get('[formcontrolname="edificio"]').select('Inluxor')
  cy.get('[formcontrolname="piso"]').select('4')
  cy.get('[formcontrolname="marca"]').type('Asus')
  cy.get('[formcontrolname="modelo"]').type('TUF')
  cy.get('[formcontrolname="serie"]').type('A1MLTFG577852')
  cy.get('[formcontrolname="codigo_barras"]').type('AsusTUFXD2')
  cy.get('#floatingHostname').type('caparaz@tcs')
  cy.get('#floatingMAC').type('1C-1B-0D-79-FF-FA')
  cy.get('#floatingIP').type('192.158.1.38')
  cy.get('#floatingReservedIP').select('Sí')
  cy.get('[formcontrolname="fecha_entrega"]').click('').type('2023-06-21')
  cy.get('.mat-dialog-actions > :nth-child(2) > .mat-button-wrapper').click('')
  cy.get('.swal2-confirm').click('')
  cy.get('#swal2-title').should('have.text','¡Error!')
  cy.get('.swal2-confirm').click('')
  
})

it('Test 10 Registro de un Activo con fecha Antigua', () => {
  cy.get('#floatingType').select('CPU/Portatil')
  cy.get('[formcontrolname="area"]').select('Recursos Humanos')
  cy.get('[formcontrolname="edificio"]').select('Inluxor')
  cy.get('[formcontrolname="piso"]').select('4')
  cy.get('[formcontrolname="marca"]').type('Asus')
  cy.get('[formcontrolname="modelo"]').type('TUF')
  cy.get('[formcontrolname="serie"]').type('A1MLTFG5')
  cy.get('[formcontrolname="codigo_barras"]').type('AsusTUFXD2')
  cy.get('#floatingHostname').type('caparaz@tcs')
  cy.get('#floatingMAC').type('1C-1B-0D-79-FF-FA')
  cy.get('#floatingIP').type('192.158.1.38')
  cy.get('#floatingReservedIP').select('Sí')
  cy.get('[formcontrolname="fecha_entrega"]').click('').type('2021-01-21')
  cy.get('.mat-dialog-actions > :nth-child(2) > .mat-button-wrapper').click('')
  cy.get('.swal2-confirm').click('')
  cy.get('#swal2-title').should('have.text','¡Error!')
  cy.get('.swal2-confirm').click('')
  
})

it('Test 11 Registro en Blanco', () => {
   
  cy.get('.mat-dialog-actions > :nth-child(2) > .mat-button-wrapper').click();
  cy.get(':nth-child(3) > :nth-child(1) > div.ng-star-inserted > .form-text').should('have.text',' * Ingrese una marca. ')
  cy.get(':nth-child(3) > :nth-child(2) > div.ng-star-inserted > .form-text').should('have.text' , ' * Ingrese un modelo. ')
  cy.get(':nth-child(4) > :nth-child(1) > div.ng-star-inserted > .form-text').should('have.text' , ' * Ingrese un número de serie. ')
  cy.get(':nth-child(4) > :nth-child(2) > div.ng-star-inserted > .form-text').should('have.text' , ' * Ingrese el código del activo. ')
  cy.get(':nth-child(1) > :nth-child(1) > div.ng-star-inserted > .form-text').should('have.text' , ' * Ingrese un nombre de host. ')
  cy.get(':nth-child(1) > :nth-child(2) > div.ng-star-inserted > .form-text').should('have.text' , ' * Ingrese una dirección MAC. ')
  cy.get(':nth-child(2) > :nth-child(1) > div.ng-star-inserted > .form-text').should('have.text' , ' * Ingrese una dirección IP. ')
  cy.get(':nth-child(6) > .col-12 > div.ng-star-inserted > .form-text').should('have.text' , ' * Seleccione una fecha válida. ')

});